-- CHANGE THE DATE TO TIMESTAMP
-- ADD PK
-- ADD PK
-- CHANGE THE LOOKUP TABLES

  DROP SEQUENCE XXBFM_CUSTOMER_SEQ;
  /
  DROP TABLE XXBFM_CUSTOMER_ALL CASCADE CONSTRAINTS;
  /
  CREATE TABLE XXBFM.XXBFM_CUSTOMER_ALL
    (
      CUSTOMER_ID       NUMBER NOT NULL,
      NAME              VARCHAR2(256),
      SITE              VARCHAR2(256),
      ADDRESS           VARCHAR2(2048) ,
      START_DATE        TIMESTAMP(6) ,
      END_DATE          TIMESTAMP(6) ,
      CREATED_BY        VARCHAR2(256) NOT NULL ,
      CREATION_DATE     TIMESTAMP(6) NOT NULL ,
      LAST_UPDATED_BY   VARCHAR2(256) NOT NULL ,
      LAST_UPDATE_DATE  TIMESTAMP(6) NOT NULL ,
      LAST_UPDATE_LOGIN VARCHAR2(32),
      TENANT_ID         NUMBER
    );
CREATE SEQUENCE XXBFM_CUSTOMER_SEQ MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 101 CACHE 20 ORDER NOCYCLE ;
  ALTER TABLE "XXBFM_CUSTOMER_ALL" ADD CONSTRAINT "XXBFM_CUSTOMER_PK" PRIMARY KEY ("CUSTOMER_ID") ENABLE;
CREATE OR REPLACE VIEW XXBFM_CUSTOMER
AS
  ( SELECT * FROM XXBFM_CUSTOMER_ALL
  )
-------------------------
DROP SEQUENCE XXBFM_CURRENCY_SEQ;
/
DROP TABLE XXBFM_CURRENCY_ALL CASCADE CONSTRAINTS;
/
CREATE TABLE XXBFM.XXBFM_CURRENCY_ALL
  (
    CURRENCY_ID       NUMBER NOT NULL,
    CURRENCY_CODE     VARCHAR2(3) NOT NULL ,
    NAME              VARCHAR2(256) NOT NULL ,
    BASE_CURRENCY     VARCHAR2(3) ,
    CONVERSION_RATE   NUMBER ,
    START_DATE        TIMESTAMP(6) ,
    END_DATE          TIMESTAMP(6) ,
    CREATED_BY        VARCHAR2(256) NOT NULL ,
    CREATION_DATE     TIMESTAMP(6) NOT NULL ,
    LAST_UPDATED_BY   VARCHAR2(256) NOT NULL ,
    LAST_UPDATE_DATE  TIMESTAMP(6) NOT NULL ,
    LAST_UPDATE_LOGIN VARCHAR2(32),
    TENANT_ID         NUMBER
  );
CREATE SEQUENCE XXBFM_CURRENCY_SEQ MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 101 CACHE 20 ORDER NOCYCLE ;
  ALTER TABLE "XXBFM_CURRENCY_ALL" ADD CONSTRAINT "XXBFM_CURRENCY_PK" PRIMARY KEY ("CURRENCY_ID") ENABLE;
CREATE OR REPLACE VIEW XXBFM_CURRENCY
AS
  ( SELECT * FROM XXBFM_CURRENCY_ALL
  );
  --------------------------------------------------
  DROP SEQUENCE XXBFM_BANK_SEQ;
  /
  DROP TABLE XXBFM_BANK_ALL CASCADE CONSTRAINTS;
  /
  CREATE TABLE XXBFM.XXBFM_BANK_ALL
    (
      BANK_ID           NUMBER NOT NULL,
      BANK_SHORTNAME    VARCHAR2(256) NOT NULL ,
      BANK_NAME         VARCHAR2(256) NOT NULL ,
      BRANCH_ADDRESS    VARCHAR2(256) NOT NULL ,
      ACCOUNTNO         VARCHAR2(256) NOT NULL ,
      START_DATE        DATE ,
      END_DATE          DATE,
      CREATED_BY        VARCHAR2(256) NOT NULL ,
      CREATION_DATE     TIMESTAMP(6) NOT NULL ,
      LAST_UPDATED_BY   VARCHAR2(256) NOT NULL ,
      LAST_UPDATE_DATE  TIMESTAMP(6) NOT NULL ,
      LAST_UPDATE_LOGIN VARCHAR2(32)
    );
CREATE SEQUENCE XXBFM_BANK_SEQ MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 101 CACHE 20 ORDER NOCYCLE ;
  ALTER TABLE "XXBFM_BANK_ALL" ADD CONSTRAINT "XXBFM_BANK_PK" PRIMARY KEY ("BANK_ID") ENABLE;
CREATE OR REPLACE VIEW XXBFM_BANK
AS
  ( SELECT * FROM XXBFM_BANK_ALL
  );
  -----------------------
  DROP SEQUENCE XXBFM_BUSINESS_ENTITY_SEQ;
  /
  DROP TABLE XXBFM_BUSINESS_ENTITY_ALL CASCADE CONSTRAINTS;
  /
  CREATE TABLE XXBFM.XXBFM_BUSINESS_ENTITY
    (
      BUSINESS_ENTITY_ID NUMBER NOT NULL ,
      BUSINESS_ENTITY    VARCHAR2(256) NOT NULL ,
      BUSINESS_GROUP     VARCHAR2(256) NOT NULL ,
      PROJECT_CODE       VARCHAR2(256) ,
      COMBINATION        VARCHAR2(1024) ,
      STATUS             VARCHAR2(256) ,
      CREATED_BY         VARCHAR2(256) NOT NULL ,
      CREATION_DATE      TIMESTAMP(6) NOT NULL ,
      LAST_UPDATED_BY    VARCHAR2(256) NOT NULL ,
      LAST_UPDATE_DATE   TIMESTAMP(6) NOT NULL ,
      LAST_UPDATE_LOGIN  VARCHAR2(32)
    );
CREATE SEQUENCE XXBFM_BUSINESS_ENTITY_SEQ MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 101 CACHE 20 ORDER NOCYCLE ;
  ALTER TABLE "XXBFM_BUSINESS_ENTITY_ALL" ADD CONSTRAINT "XXBFM_BUSINESS_ENTITY_PK" PRIMARY KEY ("BUSINESS_ENTITY_ID") ENABLE;
CREATE OR REPLACE VIEW XXBFM_BUSINESS_ENTITY
AS
  ( SELECT * FROM XXBFM_BUSINESS_ENTITY_ALL
  );
  -----------------------
  DROP SEQUENCE XXBFM_FACILITY_STRUCTURE_SEQ;
  /
  DROP TABLE XXBFM_FACILITY_STRUCTURE_ALL CASCADE CONSTRAINTS;
  /
  CREATE TABLE XXBFM.XXBFM_FACILITY_STRUCTURE
    (
      FACILITY_STRUCTURE_ID NUMBER NOT NULL ,
      FACILITY_NAME         VARCHAR2(256) NOT NULL ,
      COMPONENT             VARCHAR2(256),
      SUB_COMP              VARCHAR2(256),
      FACILITY_COMBINATION  VARCHAR2(1024),
      START_DATE            TIMESTAMP(6),
      END_DATE              TIMESTAMP(6),
      CREATED_BY            VARCHAR2(256) NOT NULL ,
      CREATION_DATE         TIMESTAMP(6) NOT NULL ,
      LAST_UPDATED_BY       VARCHAR2(256) NOT NULL ,
      LAST_UPDATE_DATE      TIMESTAMP(6) NOT NULL ,
      LAST_UPDATE_LOGIN     VARCHAR2(32)
    );
CREATE SEQUENCE XXBFM_FACILITY_STRUCTURE_SEQ MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 101 CACHE 20 ORDER NOCYCLE ;
  ALTER TABLE "XXBFM_FACILITY_STRUCTURE_ALL" ADD CONSTRAINT "XXBFM_FACILITY_STRUCTURE_PK" PRIMARY KEY ("FACILITY_STRUCTURE_ID") ENABLE;
CREATE OR REPLACE VIEW XXBFM_FACILITY_STRUCTURE
AS
  ( SELECT * FROM XXBFM_FACILITY_STRUCTURE_ALL
  );
  -----------------------
  /*DROP TABLE XXBFM.XXBFM_STATUS;
  CREATE TABLE XXBFM.XXBFM_STATUS
  (
  ID                   NUMBER NOT NULL ,
  FACILITY_COMBINATION VARCHAR2(256) NOT NULL ,
  XXLEVEL                VARCHAR2(256) ,
  SEQ                  VARCHAR2(256) ,
  STATUS               VARCHAR2(256) ,
  ALERT_API            VARCHAR2(256) ,
  APPROVAL_API         VARCHAR2(256) ,
  ACCOUNTING_API       VARCHAR2(256),
  CREATED_BY           VARCHAR2(256) NOT NULL ,
  CREATION_DATE        DATE NOT NULL ,
  LAST_UPDATED_BY      VARCHAR2(256) NOT NULL ,
  LAST_UPDATE_DATE     DATE NOT NULL ,
  LAST_UPDATE_LOGIN    VARCHAR2(32)
  );*/
  DROP SEQUENCE XXBFM_LOOKUP_TYPE_SEQ;
  /
  DROP TABLE XXBFM_LOOKUP_TYPE_ALL CASCADE CONSTRAINTS;
  /
  CREATE TABLE XXBFM.XXBFM_LOOKUP_TYPE_ALL
    (
      LOOKUP_TYPE_ID    NUMBER NOT NULL,
      LOOKUP_TYPE       VARCHAR2(256) NOT NULL ,
      DESCRIPTION       VARCHAR2(256) NOT NULL ,
      START_DATE        TIMESTAMP(6) ,
      END_DATE          TIMESTAMP(6) ,
      STATUS            VARCHAR2(256),
      CREATED_BY        VARCHAR2(256) NOT NULL ,
      CREATION_DATE     TIMESTAMP(6) NOT NULL ,
      LAST_UPDATED_BY   VARCHAR2(256) NOT NULL ,
      LAST_UPDATE_DATE  TIMESTAMP(6) NOT NULL ,
      LAST_UPDATE_LOGIN VARCHAR2(32)
    );
CREATE SEQUENCE XXBFM_LOOKUP_TYPE_SEQ MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 101 CACHE 20 ORDER NOCYCLE ;
  ALTER TABLE "XXBFM_LOOKUP_TYPE_ALL" ADD CONSTRAINT "XXBFM_LOOKUP_TYPE_PK" PRIMARY KEY ("LOOKUP_TYPE_ID") ENABLE;
  ALTER TABLE "XXBFM_LOOKUP_TYPE_ALL" ADD CONSTRAINT "XXBFM_LOOKUP_TYPE_UK" UNIQUE (LOOKUP_TYPE) ENABLE;
CREATE OR REPLACE VIEW XXBFM_LOOKUP_TYPE
AS
  ( SELECT * FROM XXBFM_LOOKUP_TYPE_ALL
  );
  -----------------------
  DROP SEQUENCE XXBFM_LOOKUP_VALUE_SEQ;
  /
  DROP TABLE XXBFM_LOOKUP_VALUE_ALL CASCADE CONSTRAINTS;
  /
  CREATE TABLE XXBFM.XXBFM_LOOKUP_VALUE_ALL
    (
      LOOKUP_VALUE_ID   NUMBER NOT NULL,
      LOOKUP_TYPE       VARCHAR2(256) NOT NULL ,
      LOOKUP_VALUE      VARCHAR2(256) NOT NULL ,
      DESCRIPTION       VARCHAR2(256) NOT NULL ,
      START_DATE        TIMESTAMP(6) ,
      END_DATE          TIMESTAMP(6) ,
      STATUS            VARCHAR2(256),
      CREATED_BY        VARCHAR2(256) NOT NULL ,
      CREATION_DATE     TIMESTAMP(6) NOT NULL ,
      LAST_UPDATED_BY   VARCHAR2(256) NOT NULL ,
      LAST_UPDATE_DATE  TIMESTAMP(6) NOT NULL ,
      LAST_UPDATE_LOGIN VARCHAR2(32)
    );
CREATE SEQUENCE XXBFM_LOOKUP_VALUE_SEQ MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 101 CACHE 20 ORDER NOCYCLE ;
  ALTER TABLE "XXBFM_LOOKUP_VALUE_ALL" ADD CONSTRAINT "XXBFM_LOOKUP_VALUE_PK" PRIMARY KEY ("LOOKUP_VALUE_ID") ENABLE;
  ALTER TABLE "XXBFM_LOOKUP_VALUE_ALL" ADD CONSTRAINT "XXBFM_LOOKUP_VALUE_UK" UNIQUE (LOOKUP_TYPE, LOOKUP_VALUE) ENABLE;
  ALTER TABLE "XXBFM_LOOKUP_VALUE_ALL" ADD CONSTRAINT "XXBFM_LOOKUP_VALUE_FK1" FOREIGN KEY ("LOOKUP_TYPE") REFERENCES "XXBFM_LOOKUP_TYPE_ALL" ("LOOKUP_TYPE") ENABLE;
CREATE OR REPLACE VIEW XXBFM_LOOKUP_VALUE
AS
  ( SELECT * FROM XXBFM_LOOKUP_VALUE_ALL
  );
  -----------------------
  DROP SEQUENCE XXBFM_DISCOUNTING_LIMIT_SEQ;
  /
  DROP TABLE XXBFM_DISCOUNTING_LIMIT_ALL CASCADE CONSTRAINTS;
  /
  CREATE TABLE XXBFM.XXBFM_DISCOUNTING_LIMIT_ALL
    (
      DISCOUNTING_LIMIT_ID NUMBER NOT NULL,
      CUSTOMER_ID          NUMBER ,
      CURRENCY_ID          VARCHAR2(256) ,
      LIMIT_VALUE          NUMBER ,
      START_DATE           TIMESTAMP(6) ,
      END_DATE             TIMESTAMP(6),
      CREATED_BY           VARCHAR2(256) NOT NULL ,
      CREATION_DATE        TIMESTAMP(6) NOT NULL ,
      LAST_UPDATED_BY      VARCHAR2(256) NOT NULL ,
      LAST_UPDATE_DATE     TIMESTAMP(6) NOT NULL ,
      LAST_UPDATE_LOGIN    VARCHAR2(32)
    );
CREATE SEQUENCE XXBFM_DISCOUNTING_LIMIT_SEQ MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 101 CACHE 20 ORDER NOCYCLE ;
  ALTER TABLE "XXBFM_DISCOUNTING_LIMIT_ALL" ADD CONSTRAINT "XXBFM_DISCOUNTING_LIMIT_PK" PRIMARY KEY ("DISCOUNTING_LIMIT_ID") ENABLE;
  ALTER TABLE "XXBFM_DISCOUNTING_LIMIT_ALL" ADD CONSTRAINT "XXBFM_DISCOUNTING_LIMIT_FK1" FOREIGN KEY ("CUSTOMER_ID") REFERENCES "XXBFM_CUSTOMER_ALL" ("CUSTOMER_ID") ENABLE;
  ALTER TABLE "XXBFM_DISCOUNTING_LIMIT_ALL" ADD CONSTRAINT "XXBFM_DISCOUNTING_LIMIT_FK2" FOREIGN KEY ("CURRENCY_ID") REFERENCES "XXBFM_CURRENCY_ALL" ("CURRENCY_ID") ENABLE;
CREATE OR REPLACE VIEW XXBFM_DISCOUNTING_LIMIT
AS
  ( SELECT * FROM XXBFM_DISCOUNTING_LIMIT_ALL
  );
  -----------------------
  DROP SEQUENCE XXBFM_FACILITY_TRACKER_SEQ;
  /
  DROP TABLE XXBFM_FACILITY_TRACKER_ALL CASCADE CONSTRAINTS;
  /
  CREATE TABLE XXBFM.XXBFM_FACILITY_TRACKER
    (
      FACILITY_TRACKER_ID   NUMBER NOT NULL,
      BANK_ID               NUMBER NOT NULL ,
      BUSINESS_ENTITY_ID    NUMBER NOT NULL ,
      FACILITY_STRUCTURE_ID NUMBER NOT NULL ,
      CURRENCY_ID           VARCHAR2(256) ,
      FACILITY_VALUE        NUMBER ,
      BANK_REFERENCE        VARCHAR2(256) ,
      START_DATE            DATE ,
      END_DATE              DATE ,
      STATUS                VARCHAR2(256) ,
      CREATED_BY            VARCHAR2(256) NOT NULL ,
      CREATION_DATE         TIMESTAMP(6) NOT NULL ,
      LAST_UPDATED_BY       VARCHAR2(256) NOT NULL ,
      LAST_UPDATE_DATE      TIMESTAMP(6) NOT NULL ,
      LAST_UPDATE_LOGIN     VARCHAR2(32)
    );
  --fk TO BANKS, BUSINESS ENTTY, FACITLITY STRU, CURRENCY
CREATE SEQUENCE XXBFM_FACILITY_TRACKER_SEQ MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 101 CACHE 20 ORDER NOCYCLE ;
  ALTER TABLE "XXBFM_FACILITY_TRACKER_ALL" ADD CONSTRAINT "XXBFM_FACILITY_TRACKER_PK" PRIMARY KEY ("FACILITY_TRACKER_ID") ENABLE;
  ALTER TABLE "XXBFM_FACILITY_TRACKER_ALL" ADD CONSTRAINT "XXBFM_FACILITY_TRACKER_FK1" FOREIGN KEY ("BANK_ID") REFERENCES "XXBFM_BANK_ALL" ("BANK_ID") ENABLE;
  ALTER TABLE "XXBFM_FACILITY_TRACKER_ALL" ADD CONSTRAINT "XXBFM_FACILITY_TRACKER_FK2" FOREIGN KEY ("BUSINESS_ENTITY_ID") REFERENCES "XXBFM_BUSINESS_ENTITY_ALL" ("BUSINESS_ENTITY_ID") ENABLE;
  ALTER TABLE "XXBFM_FACILITY_TRACKER_ALL" ADD CONSTRAINT "XXBFM_FACILITY_TRACKER_FK3" FOREIGN KEY ("FACILITY_STRUCTURE_ID") REFERENCES "XXBFM_FACILITY_STRUCTURE_ALL" ("FACILITY_STRUCTURE_ID") ENABLE;
  ALTER TABLE "XXBFM_FACILITY_TRACKER_ALL" ADD CONSTRAINT "XXBFM_FACILITY_TRACKER_FK4" FOREIGN KEY ("CURRENCY_ID") REFERENCES "XXBFM_CURRENCY_ALL" ("CURRENCY_ID") ENABLE;
CREATE OR REPLACE VIEW XXBFM_FACILITY_TRACKER
AS
  ( SELECT * FROM XXBFM_FACILITY_TRACKER_ALL
  );
  -----------------------